function [changedprops,lastprop]=i_conteq_propdlg(obj,propnr)
if nargin<1
    global g_cont;
    obj=g_cont;
end
if isempty(obj.settings.derived.frompoint)||isempty(obj.settings.derived.ctype)
    props=obj.get;
else
    props=obj.get('alloptions',obj.settings.derived.frompoint,obj.settings.derived.ctype);
end
props=props(:,1);
if nargin<2
    propnr=1;
elseif ~ischar(propnr)
    propnr=props{propnr};
end
lastprop=propnr;
changedprops={};
[~,ndx]=sort(lower(props));
props=props(ndx);
if ischar(propnr)
    propnr=find(strcmp(props,propnr));
end
hfig=figure(...
    'Units','characters',...
    'PaperUnits',get(0,'defaultfigurePaperUnits'),...
    'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
    'IntegerHandle','off',...
    'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
    'MenuBar','none',...
    'Name','Edit conteq options',...
    'NumberTitle','off',...
    'CreateFcn', @(h,evnt)movegui(h,'center') ,...
    'PaperPosition',get(0,'defaultfigurePaperPosition'),...
    'PaperSize',get(0,'defaultfigurePaperSize'),...
    'PaperType',get(0,'defaultfigurePaperType'),...
    'Position',[103.8 31 90 20],...
    'Resize','on',...
    'ResizeFcn',@resize,...
    'UserData',[],...
    'Tag','figure1',...
    'Visible','off');

uitable(...
    'Parent',hfig,...
    'Units','characters',...
    'BackgroundColor',[1 1 1],...
    'CellEditCallback',@updateprop,...
    'ColumnFormat',{  [] [] },...
    'ColumnEditable',[false,true],...
    'ColumnWidth',{  'auto' 'auto' },...
    'Rowname',[],...
    'RearrangeableColumns','on',...
    'Columnname',[],...
    'Data',[],...
    'Position',[21.4 7 36 16.8461538461538],...
    'UserData',[],...
    'Visible','off',...
    'Tag','uitable1');

h=uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'callback',@setprop,...
    'BackgroundColor',[1 1 1],...
    'Position',[21.4 27.5384615384616 25.6 1.53846153846154],...
    'String',props,...
    'Style','popupmenu',...
    'Value',propnr,...
    'Visible','on',...
    'Tag','popupprops');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'HorizontalAlignment','left',...
    'Position',[5.6 27.5384615384616 10.4 1.07692307692308],...
    'String','Parameter:',...
    'Style','text',...
    'Tag','text1' );

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'HorizontalAlignment','left',...
    'Position',[5.6 22 10.4 1.07692307692308],...
    'String','Value:',...
    'Style','text',...
    'Tag','text2' );

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'callback',@updateprop,...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left',...
    'Position',[21.4 22 36.2 1.69230769230769],...
    'String','',...
    'Style','edit',...
    'Tag','EditValue1');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'BackgroundColor',[1 1 1],...
    'callback',@updateprop,...
    'Position',[21.4 22 36.2 1.53846153846154],...
    'String',{  'Pop-up Menu' },...
    'Style','popupmenu',...
    'Value',[],...
    'Tag','popupValue1');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'HorizontalAlignment','left',...
    'Position',[21.4 24.9230769230769 150 1.07692307692308],...
    'String','Description',...
    'Style','text',...
    'Tag','DescriptionText' );

% uicontrol(...
%     'Parent',hfig,...
%     'Units','characters',...
%     'Position',[16 1.23076923076923 13.8 1.69230769230769],...
%     'String','Cancel',...
%     'Tag','pushbutton1');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'Callback',@okpressed,...
    'Position',[20 1.15384615384615 13.8 1.69230769230769],...
    'String','OK',...
    'Tag','pushbutton2' );

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'BackgroundColor',[1 1 1],...
    'callback',@updateprop,...
    'HorizontalAlignment','left',...
    'Position',[21.4 19 36.2 1.69230769230769],...
    'String',{  'Edit Text' },...
    'Style','edit',...
    'Tag','EditValue2');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'callback',@updateprop,...
    'BackgroundColor',[1 1 1],...
    'Position',[21.4 19 36.2 1.53846153846154],...
    'String',{  'Pop-up Menu' },...
    'Style','popupmenu',...
    'Value',[],...
    'Tag','popupValue2');
resize(hfig);
setprop(h);
set(hfig,'Visible','on')
uiwait(hfig);
changedprops=unique(changedprops);

    function setprop(hObj,~)
        hfig1=get(hObj,'parent');
        h1=findobj(hfig1,'Tag','popupprops');
        aval=get(h1,'Value');
        if isempty(aval)
            aval=1;
        end
        str=get(h1,'String');
        prop=str{aval};
        proptype=obj.get('-properties',prop);
        h1=findobj(hfig1,'Tag','DescriptionText');
        set(h1,'string',proptype.descr);
        tags={'uitable1','EditValue1','popupValue1','EditValue2','popupValue2'};
        for i=1:length(tags)
            set(findobj(hfig1,'Tag',tags{i}),'Visible','off');
        end
        if strcmp(proptype.type ,'l#E')
            if isempty(proptype.value)
                v=2;
            else
                v=double(proptype.value);
            end
            setItem(hfig1,'popupValue1','value',v+1,'string',{'false','true','[]'})
        elseif strcmpi(proptype.name,'BranchingPars')
            bp=get(obj,'BranchingPars');
            bps=false(1,numel(obj.settings.derived.allpars));
            bps(bp)=true;
            data=[obj.settings.derived.allpars;num2cell(bps)]';
            setItem(hfig1,'uitable1','data',data,'ColumnName',{'Parameter','Active'},'ColumnWidth',{150,70})
        elseif strcmpi(proptype.name,'activepars')
            data=[obj.settings.derived.allpars;num2cell(obj.settings.grind.activepars)]';
            setItem(hfig1,'uitable1','data',data,'ColumnName',{'Parameter','Active'},'ColumnWidth',{150,70})
        elseif any(strcmpi(proptype.name,{'UserfunctionsInfo','Userhandles'}))
            Userfuncts=obj.get('UserfunctionsInfo');
            Userhands=obj.get('Userhandles');
            if ~isempty(Userfuncts)
                data=struct2cell(Userfuncts(:));
                data=reshape(data,[3,numel(Userfuncts)])';
                if ~isempty(Userhands)
                    if ~iscell(Userhands)
                        Userhands={Userhands};
                    end
                    for i=1:length(Userhands)
                        Userhands{i}=func2str(Userhands{i});
                    end
                    Userhands=Userhands(:);
                else
                    Userhands=repmat({''},size(data,1));
                end
                data=[data, Userhands];
                data(end+1,:)={'',true,'',''};
            else
                data={'',true,'',''};
            end
            setItem(hfig1,'uitable1','data',data,'ColumnName',{'name','state',...
                'label','Userhandles'},'ColumnWidth',{70,70,70,140},'ColumnEditable',[true,true,true,true],...
                'CellEditCallback',@updateuserhandles)
        elseif strcmpi(proptype.name,'IgnoreSingularity')&&any(strcmp(obj.settings.derived.engine,{'matcont','matcontm'}))
            ndx=obj.getndx('curveprops','ctype',obj.settings.derived.ctype);
            singlist=obj.curveprops(ndx).singularity';
            for i=1:length(singlist)
                descr=obj.pointprops(obj.getndx('pointprops','ptype',singlist{i})).descr;
                singlist{i}=sprintf('%s - %s',singlist{i},descr);
            end
            data=[singlist num2cell(true(size(singlist)))];
            proptype.value=proptype.value(proptype.value<=numel(singlist));
            data(proptype.value,2)={false};
            setItem(hfig1,'uitable1','data',data,'ColumnName',{'Singularity','Active'},'ColumnWidth',{150,70})
        elseif strcmp(proptype.type, 'l')
            setItem(hfig1,'popupValue1','value',proptype.value+1,'string',{'false','true'})
        elseif strcmp(proptype.type, 'p')
            pars=obj.settings.derived.allpars(obj.settings.grind.activepars);
            setItem(hfig1,'popupValue1','value',find(strcmp(proptype.value,pars)),'string',pars)
        elseif strcmp(proptype.type, 'p#E')
            pars=[{''} obj.settings.derived.allpars(obj.settings.grind.activepars)];
            v=find(strcmp(proptype.value,pars));
            if isempty(v)
                v=1;
            end
            setItem(hfig1,'popupValue1','value',v,'string',pars)
        elseif strcmp(proptype.type, 'n&length(n)==2')
            s=any2str(proptype.value(1));
            if strcmpi(s,'NaN')
                s='';
            end
            setItem(hfig1,'EditValue1','string',s)
            s=any2str(proptype.value(2));
            if strcmpi(s,'NaN')
                s='';
            end
            setItem(hfig1,'EditValue2','string',s)
        else
            s=any2str(proptype.value);
            if strcmpi(s,'NaN')
                s='';
            end
            setItem(hfig1,'EditValue1','string',s)
        end
    end

    function updateuserhandles(hObj,~)
        hfig1=get(hObj,'parent');
        visib_tags=get(findobj(hfig1,'Visible','on'),'tag');
        if any(strcmp(visib_tags,'uitable1'))
            h1=findobj(hfig1,'tag','uitable1');
            data=get(h1,'data');
            ndx=true(size(data,1),1);
            for j=1:size(data,1)
                if isempty(data{j,1})||isempty(data{j,3})||isempty(data{j,4})
                    ndx(j)=false;
                end
            end
            if all(ndx)
                data1=data;
                data1(end+1,:)={'',true,'',''};
                set(h1,'data',data1)
            end
            data=data(ndx,:);
            if ~isempty(data)
                obj.set('Userfunctions',true);
                obj.set('UserfunctionsInfo',struct('name',data(:,1)','state',data(:,2)','label',data(:,3)'));
                obj.set('Userhandles',data(:,4)');
            else
                obj.set('Userfunctions',false);
            end
        end
    end


    function updateprop(hObj,~)
        hfig1=get(hObj,'parent');
        visib_tags=get(findobj(hfig1,'Visible','on'),'tag');
        s='';
        h1=findobj(hfig1,'Tag','popupprops');
        aval=get(h1,'Value');
        str=get(h1,'String');
        prop=str{aval};
        if any(strcmp(visib_tags,'popupValue1'))
            h1=findobj(hfig1,'tag','popupValue1');
            str=get(h1,'string');
            v=get(h1,'value');
            s=[s str{v}];
        end
        if any(strcmp(visib_tags,'uitable1'))
            h1=findobj(hfig1,'tag','uitable1');
            data=get(h1,'data');
            if strcmpi(prop,'IgnoreSingularity')
                v=find(~[data{:,2}]);
                if isempty(v)
                    s='[]';
                else
                    s=mat2str(v);
                end
            elseif strcmp(prop,'BranchingPars')
                v=find([data{:,2}]);
                if isempty(v)
                    s='[]';
                else
                    s=mat2str(v);
                end
            elseif strcmp(prop,'activepars')
                v=[data{:,2}];
                s=mat2str(v);
            end
        end
        if any(strcmp(visib_tags,'EditValue1'))
            h1=findobj(hfig1,'tag','EditValue1');
            s1=get(h1,'string');
            if isempty(s1)
                s1='NaN';
            end
            s=[s s1];
        end
        if any(strcmp(visib_tags,'EditValue2'))
            h1=findobj(hfig1,'tag','EditValue2');
            s1=get(h1,'string');
            if isempty(s1)
                s1='NaN';
            end
            s=sprintf('[%s %s]',s,s1);
        end
        oldprop=obj.get(prop);
        try
            obj.set(prop,s);
            changedprops{end+1}=prop;
        catch err
            obj.set(prop,oldprop);
            rethrow(err)
        end
    end

    function setItem(hfig1,tag,varargin)
        h1=findobj(hfig1,'Tag',tag);
        set(h1,'Visible','on')
        set(h1,varargin{:});
    end

    function okpressed(hobj,~)
        hfig=getparentfig(hobj);
        h1=findobj(hfig,'Tag','popupprops');
        aval=get(h1,'Value');
        if isempty(aval)
            aval=1;
        end
        str=get(h1,'String');
        lastprop=str{aval};
        uiresume(hfig)
        close(hfig)
    end

    function resize(hobj,~)
        hfig=getparentfig(hobj);
        data={...
            'uitable1',[1 1 1 1],[80.25 37 230 190];...
            'popupprops',[1 1 1 0],[80.25 268.5 96 15];...
            'text1',[1 0 1 0],[21 268.5 39 10.5];...
            'text2',[1 0 1 0],[21 214.5 39 10.5];...
            'EditValue1',[1 1 1 0],[80.25 214.5 135.75 16.5];...
            'popupValue1',[1 1 1 0],[80.25 214.5 135.75 15];...
            'DescriptionText',[1 1 1 0],[80.25 243 562.5 10.5];...
            'pushbutton2',[1 0 0 1],[80.25 10 51.75 16.5];...
            'EditValue2',[1 1 1 0],[80.25 185.25 135.75 16.5];...
            'popupValue2',[1 1 1 0],[80.25 185.25 135.75 15];...
            };
        i_resizedlg(hfig,data(:,1),data(:,2),data(:,3),[342.75 132.75 337.5 292.5]);
    end
end
%
