function g_grind=i_init_g_grind
g_grind=struct('model',{{}},...
    'modelndx',[],...
    'commands', {{}},...
    'scheme', {{}},...
    'inifile','',...
    'odefile','',...
    'boxcar',struct('names',{{}},'gcycl',[]),...
    'checks',struct('lastsettings',[],'no',zeros(4,1,'uint16'),'modelchecked',0),...
    'cont',struct('engine','matcont'),...
    'definespace',{{}},...
    'diffto','Time (t)',...
    'drawnow', 1,...
    'externvars',{{}},...
    'event',struct('queue',[],'events',[],'t',0),...
    'funcs',[],...
    'funcnames',struct('names', {{}}),...
    'figopts',{{}},...
    'hfun',struct('curr',[]),...
    'ndays', 1000,...
    'onstart',struct('funs',{{}}),...
    'outt',{{}},...
    'pars', {{}},...
    'pen', i_nextpen([]),...
    'permanent',{{}},...
    'slowdown',0,...
    'solver', struct('name', 'ode45','isdiffer',false,'opt', odeset,'iters',1,'backwards', false,'addmode',false,'hasevents', false,'haslags', false,'eulerneeded',false,'nonautonomous',false,'isinteger', false,'isimplicit', false,'iscomplex',false,'isstochastic',false,'reset_at_data',false),...
    'statevars',struct('names', {{}},'vectnames',{{}},'dims',{{}},'dim',0,'vector',0),...
    'syms', struct('fulleq', {{}},'Jacobian', {{}},'Hessian', {{}},'der3', {{}},'der4', {{}},'der5', {{}},...
    'Jacobianp', {{}},'Hessianp', {{}},'Sensitivp', {{}},'errormsg', {{}}),...
    'timevars', {{}},...
    'truncate',false,...
    'tstep', NaN,...
    'xaxis',struct('var',[],'lim',[0 10]),...
    'yaxis',struct('var',[],'lim',[0 10]),...
    'zaxis',struct('var',[],'lim',[0 10]));


g_grind.solver.opt.RelTol=5e-5;
g_grind.solver.opt.AbsTol=1e-7;
g_grind.solver.opt.StepSize=0.1;
g_grind.solver.opt.NonNegative=[];
g_grind.solver.opt.Vectorized=[];
