function i_matrixmovie(par1, par2, par3)
if nargin == 0
    par1 = rand(10, 50, 50);
end

ud.data = par1;
if any(~isreal(ud.data(:)))
    warning('grind:matrixmovie','Imaginary parts of complex values ignored');
    ud.data=real(ud.data);
end
ud.running = 0;
ud.xlabel={};
ud.ylabel={};
h1 = figure( ...
    'PaperUnits',get(0,'defaultfigurePaperUnits'),...
    'Color', [0.941176470588235 0.941176470588235 0.941176470588235], ...
    'Colormap',get(0,'defaultfigureColormap'),...
    'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
    'PaperPosition', [0.6345175 6.345175 20.30456 15.22842], ...
    'PaperSize',get(0,'defaultfigurePaperSize'),...
    'PaperType',get(0,'defaultfigurePaperType'),...
    'Position',get(0,'defaultfigurePosition'),...
    'WindowButtonMotionFcn',@c_mousemove);
dat=ud.data(end,:,:);
maxc=max(abs(dat(~isnan(dat))));
if isempty(maxc)
    maxc=1;
end
if maxc==0
    maxc=0.1;
end

% maxc=max(abs(min(min(ud.data(end,:,:)))), max(max(ud.data(end,:,:))));
h2 = axes( ...
    'Parent', h1, ...
    'FontUnits','pixels',...
    'Position', [0.107142857142857 0.161904761904762 0.8 0.8], ...
    'Box','on',...
    'CameraPosition', [25.5 25.5 9.16025403784439], ...
    'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
    'Color',get(0,'defaultaxesColor'),...
    'ColorOrder',get(0,'defaultaxesColorOrder'),...
    'FontSize', 13.3333333333333, ...
    'Layer','top',...
    'LooseInset', [0.13 0.11 0.218809523809524 0.075], ...
    'XColor',get(0,'defaultaxesXColor'),...
    'XLim', [0.5 size(ud.data, 3) + 0.5], ...
    'Clim', [-maxc maxc],...
    'XTick',getintegertix(1,size(ud.data, 3)),...
    'TickDir','out',...
    'XLimMode','manual',...
    'YColor',get(0,'defaultaxesYColor'),...
    'YDir','reverse',...
    'YLim', [0.5 size(ud.data, 2) + 0.5], ...
    'YTick',getintegertix(1,size(ud.data, 2)),...
    'YLimMode','manual',...
    'ZColor',get(0,'defaultaxesZColor') );
image( ...
    'Parent', h2, ...
    'CData', reshape(ud.data(1, :, :), size(ud.data, 2), size(ud.data, 3)), ...
    'CDataMapping','scaled',...
    'XData', [1 size(ud.data, 3)], ...
    'YData', [1 size(ud.data, 2)], ...
    'tag','Imagesc');
if nargin>2
    ud.xlabel=par2;
    ud.ylabel=par3;
    set(gca,'XTickLabel',par2(getintegertix(1,size(ud.data, 3))));
    set(gca,'YTickLabel',par3(getintegertix(1,size(ud.data, 2))));
end

colorbar;
redgreen=interp1([1;33;65],[1 0 0;1 1 1;0 0.5 0],(1:65));
colormap(redgreen)
uicontrol( ...
    'Parent', h1, ...
    'Units','normalized',...
    'FontUnits','pixels',...
    'BackgroundColor', [0.9 0.9 0.9], ...
    'Callback',@(h,ev)c_update(h,ev,0),...
    'FontSize', 10.6666666666667, ...
    'Position', [0.248214285714286 0.00238095238095238 0.375 0.0428571428571429], ...
    'String',{  'Slider' },...
    'Tooltipstring','Use slider to select a frame',...
    'Style','slider',...
    'Max', size(ud.data, 1), ...
    'Min', 1, ...
    'SliderStep', [1 1], ...
    'Value', 1, ...
    'Tag','slider1' );
uicontrol( ...
    'Parent', h1, ...
    'Units','normalized',...
    'FontUnits','pixels',...
    'Callback',@(h,ev)c_activate(h,ev,1),...
    'FontSize', 10.6666666666667, ...
    'Position', [0.735714285714286 0 0.0375 0.0547619047619048], ...
    'String','>',...
    'Tooltipstring','Play movie forward',...
    'Tag','pushbutton1');
uicontrol( ...
    'Parent', h1, ...
    'Units','normalized',...
    'FontUnits','pixels',...
    'Callback',@(h,ev)c_activate(h,ev,-1),...
    'FontSize', 10.6666666666667, ...
    'Position', [0.623214285714286 0 0.0375 0.0547619047619048], ...
    'String','<',...
    'Tooltipstring','Play movie backwards',...
    'Tag','pushbutton2');
uicontrol( ...
    'Parent', h1, ...
    'Units','normalized',...
    'Callback',@c_deactivate,...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [0.673214285714286 0 0.0571428571428571 0.0547619047619048], ...
    'String','||||',...
    'Tooltipstring','Stop playing the movie',...
    'Tag','pushbutton3');
set(h1, 'userdata', ud);
function c_update(hobject,~,par1)
hfig=getparentfig(hobject);
ud = get(hfig, 'userdata');
h=findobj(hfig,'Tag','slider1');
step = round(get(h, 'value')) + par1;
if step < 1
    step = 1;
end

if step > size(ud.data, 1)
    step = size(ud.data, 1);
end

set(h, 'value', step);
h1=findobj(hfig,'Tag','Imagesc');
set(h1, 'CData', reshape(ud.data(step, :, :), size(ud.data, 2), size(ud.data, 3)));
function c_activate(hobject,eventdata,par1)
hfig=getparentfig(hobject);
ud = get(hfig, 'userdata');
ud.running = 1;
ud.step = par1;
set(hfig, 'userdata', ud);
c_run(hobject,eventdata);
function c_deactivate(hobject,~)
hfig=getparentfig(hobject);
ud = get(hfig, 'userdata');
ud.running = 0;
set(hfig, 'userdata', ud);
function c_mousemove(hobject,~)
hfig=getparentfig(hobject);
ud = get(hfig, 'userdata');
hax = get(hfig, 'CurrentAxes');
h=findobj(hfig,'Tag','slider1');
aval = round(get(h, 'value'));
initpt = get(hax, 'CurrentPoint');
x=round(initpt(1,1));
y=round(initpt(1,2));
if (x>0) && (y>0) && (x<=size(ud.data,3)) && (y<=size(ud.data,2))
    if isempty(ud.xlabel)
        set(hfig,'name',sprintf('matrixmovie - [%d, %d] = %g',x,y,ud.data(aval,y,x)));
    else
        set(hfig,'name',sprintf('matrixmovie - [%s, %s] = %g',ud.xlabel{x},ud.ylabel{y},ud.data(aval,y,x)));
    end

end

function c_run(hobject,eventdata)
hfig=getparentfig(hobject);
ud = get(hfig, 'userdata');
if ~isempty(ud)
    h=findobj(hfig,'Tag','slider1');
    aval = round(get(h, 'value')) + ud.step;
    while ud.running && (aval > 0) && (aval<=size(ud.data, 1))
        c_update(hobject,eventdata, ud.step);
        pause(0.3);
        ud1 = get(hfig, 'userdata');
        if isempty(ud1)
            ud.running=0;
        else
            ud=ud1;
        end

        aval = aval + ud.step;
    end

    ud.running=0;
    set(hfig,'userdata',ud);
end

function res=getintegertix(amin,amax)
amin=round(amin);
amax=round(amax);
range=amax-amin;
if range<14
    res=amin:amax;
else
    for i=7:14
        if rem(range,i)==0
            res=amin:range/i:amax;
            return;
        end

    end

    res=amin:round(range/11):amax;
end

