function fig = i_oldseteventdlg()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.


hfig = figure('Units','points', ...
	'Color',[0.914 0.914 0.914], ...
	'CreateFcn','i_setevent(''filldlg'')', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[228.75 230.25 473.25 221.25], ...
   'Name','Setevent',...
   'MenuBar','none',...
   'NumberTitle','off',...
   'Tag','Fig1', ...
 ...%  'WindowStyle','modal', ...
	'ToolBar','none',...
    'CreateFcn',@(h,evnt)movegui(h, 'center'));

uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'Position',[33.75 18 350.25 146.25], ...
	'String',' ', ...
   'Style','listbox', ...
   'Callback','i_setevent(''ListButtonDwn'')',...
	'Tag','EventsList', ...
	'Value',1);
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Callback','i_setevent(''ClearallButton'')', ...
	'ListboxTop',0, ...
	'Position',[392.25 82.34999999999999 66.75 26.25], ...
	'String','Clear all', ...
	'Tag','ClearAllBtn');
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Callback','i_setevent(''DeleteButton'')', ...
	'ListboxTop',0, ...
	'Position',[392.25 114.9 66.75 26.25], ...
	'String','Delete', ...
	'Tag','DeleteBtn');
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Callback','i_setevent(''AddButton'')', ...
	'ListboxTop',0, ...
	'Position',[393 147.75 66.75 26.25], ...
	'String','Add', ...
   'Tag','Pushbutton1');

uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[135.75 172.5 61.5 15], ...
	'Style','edit', ...
   'Tag','TimeEdit');
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[35.25 171.75 92.25 16.5], ...
	'Style','edit', ...
   'Tag','EventEdit');
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[207.75 173.25 176.25 15], ...
	'Style','edit', ...
	'Tag','ArgEdit');
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[0.914 0.914 0.914], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[35.25 190.5 45.75 10.5], ...
	'String','Event name', ...
	'Style','text', ...
	'Tag','StaticText1');
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[0.914 0.914 0.914], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[135.75 189 42.75 12], ...
	'String','First time', ...
	'Style','text', ...
	'Tag','StaticText1');
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[0.914 0.914 0.914], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[207.75 189 63 12], ...
	'String','(extra arguments)', ...
	'Style','text', ...
   'Tag','StaticText1');
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Callback','Close', ...
	'ListboxTop',0, ...
	'Position',[392.25 49.8 66.75 26.25], ...
	'String','OK', ...
	'Tag','OKbutton');
uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Callback','i_setevent(''EditButton'')', ...
	'ListboxTop',0, ...
	'Position',[392.25 180 66.75 26.25], ...
	'String','Edit', ...
	'Tag','EditButton');
if nargout > 0, fig = hfig; end
