function fig = i_optimpardlg()

h0 = figure('Units','points', ...
   	'Color',[0.914 0.914 0.914], ...
   	'MenuBar','none', ...
   	'Name','Optimpars', ...
   	'NumberTitle','off', ...
   	'PaperPosition',[18 180 576 432], ...
   	'PaperUnits','points', ...
   	'Position',[274 229 270 232], ...
   	'RendererMode','manual', ...
   	'Tag','Fig1', ...
   	'ToolBar','none', ...
    'CreateFcn',@(h,evnt)movegui(h, 'center'));

uicontrol('Parent',h0, ...
   	'Units','points', ...
   	'BackgroundColor',[1 1 1], ...
   	'HorizontalAlignment','left', ...
   	'ListboxTop',0, ...
   	'Max',30, ...
   	'Position',[1 26 266 201], ...
   	'Style','edit', ...
    'Tooltipstring','Progress of optimization',...
   	'Tag','ProgressEdit');
uicontrol('Parent',h0, ...
   	'Units','points', ...
   	'ListboxTop',0, ...
   	'Position',[152 3 55 18], ...
      'String','Stop', ...
    'Tooltipstring','Stop optimization and save the optimal parameter set',...
      'Callback','evalin(''base'',''g_data.stopped=1;'')',...
   	'Tag','Pushbutton1');
uicontrol('Parent',h0, ...
   	'Units','points', ...
   	'ListboxTop',0, ...
   	'Position',[80 3 55 18], ...
   	'String','Cancel', ...
     'Tooltipstring','Cancel optimization, no change in parameters',...
     'Callback','evalin(''base'',''g_data.stopped=2;'')',...
   	'Tag','Pushbutton2');


if nargout > 0, fig = h0; end
