function fig = i_paranaloutdlg(par1)
global g_grind;
plotfield='plots';
if nargin<1
    par1='Edit Plots for Paranal';
elseif nargin>0&&strcmp(par1,'paranal2d')
    par1='Edit Plots for Paranal';
    plotfield='plots2d';
end

if ~isempty(g_grind)&&~isfield(g_grind,'paranal')
    paranal('-defaults');
end

if ~isempty(g_grind)
    N=length(g_grind.paranal.(plotfield));
else
    N=1;
end

plotlst=cell(1,N);
for i = 1:N
    plotlst{i} = sprintf('Plot No. %d', i);
end

hfig = figure('Units','points', ...
    'Color',[0.914 0.914 0.914], ...
    'MenuBar','none', ...
    'Name',par1, ...
    'NumberTitle','off', ...
    'PaperPosition',[18 180 576 432], ...
    'PaperType','A4', ...
    'PaperUnits','points', ...
    'Position',[198  214  366 244.5], ...
    'Tag','vectplotdlg', ...
    'ToolBar','none',...
    'CreateFcn',@(h,evnt)movegui(h, 'center'));
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[17 130 163.5 18], ...
    'String','Y-axis: state variable or function (or list)', ...
    'Style','text', ...
    'Tag','StaticText2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Callback',@c_changeplot, ...
    'ListboxTop',0, ...
    'Position',[105 205.5 113.25 22.5], ...
    'String',plotlst, ...
    'Style','popupmenu', ...
    'Tag','PlotNo', ...
    'TooltipString','Select Plot number here', ...
    'Value',1);
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[17 206 72.75 18], ...
    'String','Plot No.', ...
    'Style','text', ...
    'Tag','StaticText1');

uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_newplot, ...
    'ListboxTop',0, ...
    'Position',[243 205.5 93.75 22.5], ...
    'String','Add Plot', ...
    'Tag','AddBtn', ...
    'TooltipString','Add new plot to the list of plots');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[17 175 190 18], ...
    'String','X-axis: function or <param1> for control parameter', ...
    'Style','text', ...
    'Tag','StaticText2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[17 161 190 18], ...
    'Style','edit', ...
    'Tag','EditX', ...
    'TooltipString','Edit the variable for the X axis here');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[245 175 69 18], ...
    'String','Range X axis', ...
    'Style','text', ...
    'Tag','StaticText2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[245 161 100 18], ...
    'Style','edit', ...
    'Tag','EditXlim', ...
    'TooltipString','Edit the limits for the X axis here');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[17 76 174 18], ...
    'String','Z-axis, state variable or function (or list)', ...
    'Style','text', ...
    'Tag','StaticText2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Max',1, ...
    'Position',[17 117 190 18], ...
    'Style','edit', ...
    'Tag','EditY', ...
    'TooltipString','Enter here a list of variables or functions for the Y-axis');

uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[245 130 69 18], ...
    'String','Range Y axis', ...
    'Style','text', ...
    'Tag','StaticText2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[245 117 100 18], ...
    'Style','edit', ...
    'Tag','EditYlim', ...
    'TooltipString','Edit the limits for the Y axis here');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Max',1, ...
    'Position',[17 63 190 18], ...
    'Style','edit', ...
    'Tag','EditZ', ...
    'TooltipString','Enter here a variable or function for the Z-axis');

uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[245 76 69 18], ...
    'String','Range Z axis', ...
    'Style','text', ...
    'Tag','StaticText2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[245 63 100 18], ...
    'Style','edit', ...
    'Tag','EditZlim', ...
    'TooltipString','Edit the limits for the Z axis here');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_ok, ...
    'ListboxTop',0, ...
    'Position',[31.5 8.25 93.75 22.5], ...
    'String','OK', ...
    'Tag','OKBtn', ...
    'TooltipString','Close and save');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_cancel, ...
    'ListboxTop',0, ...
    'Position',[141 8.25 93.75 22.5], ...
    'String','Cancel', ...
    'Tag','CancelBtn', ...
    'TooltipString','Close and undo changes');
if strcontains(par1,'conteq')
    uicontrol('Parent',hfig, ...
        'Units','points', ...
        'Callback','commands paranal', ...
        'ListboxTop',0, ...
        'Position',[250.5 8.25 93.75 22.5], ...
        'String','Help', ...
        'Tag','HelpBtn', ...
        'TooltipString','Open help window');
else
    uicontrol('Parent',hfig, ...
        'Units','points', ...
        'Callback','commands conteq', ...
        'ListboxTop',0, ...
        'Position',[250.5 8.25 93.75 22.5], ...
        'String','Help', ...
        'Tag','HelpBtn', ...
        'TooltipString','Open help window');
end



%if N==1
%   set(hplotno,'Enable','off');
% end

%    global g_grind;
if ~isempty(g_grind)
    ud.oudlist=g_grind.paranal.(plotfield);
else
    ud.oudlist={};
end

if isfield(ud,'curr')
    ud.curr=g_grind.paranal.currno;
else
    ud.curr=1;
end

ud.plotfield=plotfield;
set(hfig,'userdata',ud);
setplot(ud.curr,hfig,plotfield);
if nargout > 0, fig = hfig; end

uiwait(hfig);
if ishandle(hfig)
    delete(hfig);
    disp(' ');
    if ~strcontains(par1,'conteq')
        if strcmp(ud.plotfield,'plots')
            paranal('-list');
        else
            paranal2d('-list');
        end

    else
        conteq('-list')
    end

end

function c_ok(hobject,~)
%    global g_grind;
hfig=getparentfig(hobject);
ud=get(hfig,'userdata');
savecurrent(hfig,ud.curr,ud.plotfield);
uiresume(hfig);

function c_cancel(hobject,~)
global g_grind;
hfig=getparentfig(hobject);
ud=get(hfig,'userdata');
%    global g_grind;
g_grind.paranal.(ud.plotfield)=ud.oudlist;
delete(hfig);
disp('Cancelled');
%paranal('-list');
function c_newplot(hobject,~)
hfig=getparentfig(hobject);
h=findobj(hfig,'Tag','PlotNo');
plotlst = get(h,'string');
No=length(plotlst)+1;
plotlst{No} = sprintf('Plot No. %d', No);
if No>1
    set(h,'Enable','on');
end

set(h,'string',plotlst);
set(h,'value',No);
c_changeplot(h);
function c_changeplot(hobject,~)
hfig=getparentfig(hobject);
ud=get(hfig,'userdata');
savecurrent(hfig,ud.curr,ud.plotfield);
h=findobj(hfig,'tag','PlotNo');
v=get(h,'Value');
setplot(v,hfig,ud.plotfield);
ud.curr=v;
set(hfig,'userdata',ud);


function savecurrent(hfig,No,plotfield)
global g_grind;
if length(g_grind.paranal.(plotfield))<No || ~isfield(g_grind.paranal.(plotfield){No},'xlim')
    g_grind.paranal.(plotfield){No}.xaxis='';
    g_grind.paranal.(plotfield){No}.xlim=[];
    g_grind.paranal.(plotfield){No}.yaxis='';
    g_grind.paranal.(plotfield){No}.ylim=[];
    g_grind.paranal.(plotfield){No}.zaxis='';
    g_grind.paranal.(plotfield){No}.zlim=[];
end

h=findobj(hfig,'tag','EditX');
g_grind.paranal.(plotfield){No}.xaxis=mystr2cell(get(h,'string'));
h=findobj(hfig,'tag','EditY');
g_grind.paranal.(plotfield){No}.yaxis=mystr2cell(get(h,'string'));
h=findobj(hfig,'tag','EditZ');
g_grind.paranal.(plotfield){No}.zaxis=mystr2cell(get(h,'string'));
h=findobj(hfig,'tag','EditXlim');
g_grind.paranal.(plotfield){No}.xlim=checklim(g_grind.paranal.(plotfield){No}.xlim,get(h,'string'));
h=findobj(hfig,'tag','EditYlim');
g_grind.paranal.(plotfield){No}.ylim=checklim(g_grind.paranal.(plotfield){No}.ylim,get(h,'string'));
h=findobj(hfig,'tag','EditZlim');
g_grind.paranal.(plotfield){No}.zlim=checklim(g_grind.paranal.(plotfield){No}.zlim,get(h,'string'));
if (isempty(g_grind.paranal.(plotfield){No}.zaxis)||isempty(g_grind.paranal.(plotfield){No}.zaxis{1}))&&...
        (isempty(g_grind.paranal.(plotfield){No}.yaxis)||isempty(g_grind.paranal.(plotfield){No}.yaxis{1}))
    g_grind.paranal.(plotfield)(No)=''; %remove empty plot
    No=1;
end

g_grind.paranal.currno=No;
g_grind.paranal.defaultplots=0;

function setplot(No,hfig, plotfield)
global g_grind;
if isempty(g_grind)||(No>length(g_grind.paranal.(plotfield)))
    x='<param1>';
    y='';
    z='';
    xlim='[0 10]';
    ylim=xlim;
    zlim=xlim;
else
    x = mycell2str(g_grind.paranal.(plotfield){No}.xaxis);
    y = mycell2str(g_grind.paranal.(plotfield){No}.yaxis);
    z = mycell2str(g_grind.paranal.(plotfield){No}.zaxis);
    if isempty(g_grind.paranal.(plotfield){No}.xlim)
        xlim='[]';
    else
        xlim = sprintf('[%g %g]',g_grind.paranal.(plotfield){No}.xlim);
    end

    if isempty(g_grind.paranal.(plotfield){No}.ylim)
        ylim='[]';
    else
        ylim = sprintf('[%g %g]',g_grind.paranal.(plotfield){No}.ylim);
    end

    if isempty(g_grind.paranal.(plotfield){No}.zlim)
        zlim='[]';
    else
        zlim = sprintf('[%g %g]',g_grind.paranal.(plotfield){No}.zlim);
    end

end

h=findobj(hfig,'tag','EditX');
set(h,'string',x);
h=findobj(hfig,'tag','EditY');
set(h,'string',y);
h=findobj(hfig,'tag','EditZ');
set(h,'string',z);
h=findobj(hfig,'tag','EditXlim');
set(h,'string',xlim);
h=findobj(hfig,'tag','EditYlim');
set(h,'string',ylim);
h=findobj(hfig,'tag','EditZlim');
set(h,'string',zlim);
h=findobj(hfig,'tag', 'PlotNo');
set(h,'value',No);

function A=mystr2cell(s)
%s=strrep(s,',',sprintf('\n')); This gives problems if a comma is in the
%equation
A=str2cell(strrep(s,' ',sprintf('\n')));  %#ok<SPRINTFN>
f=strcmp(A,'');
A(f)=[];
if isempty(A)
    A={''};
end

A=i_getoutlist(A);
for i=1:length(A)
    A{i}=outf('changeshortcut', A{i});
end



function s=mycell2str(A)
s=strtrim(sprintf('%s ',A{:}));

function lim=checklim(~,slim)
lim=str2num(slim); 
if isnan(lim)
    lim=[];
end

if length(lim)~=2
    lim=[];
elseif lim(1)>lim(2)
    h=lim(2);
    lim(2)=lim(1);
    lim(1)=h;
end



