function selndx = i_parseldlg( pars, Li, perc, critvals)
if nargin == 0
    pars={};
    Li=[];
    perc=[0.05 0.25 0.5 0.75 0.95];
    critvals=zeros(size(perc));
end

[~,ndx] = sort(Li);
ud.pars=pars;
sortedpars=pars(ndx);
f=find(perc>0.5);
perc=perc(f);
ud.Li=Li;
ud.critvals=[-9999;transpose(critvals(f))];
ps=cell(1,length(perc)+1);
ps{1}='all';
for i=1:length(perc)
    ps{i+1}=sprintf('p<%g',1-perc(i));
end

hfig = figure('Units','points', ...
    'MenuBar','none', ...
    'Name','Select parameters for dendrogram', ...
    'NumberTitle','off', ...
    'Color',[0.914 0.914 0.914], ...
    'PaperPosition',[18 180 576 432], ...
    'PaperUnits','points', ...
    'Position',[194.25 159.75 420 315], ...
    'Tag','parseldlg', ...
    'ToolBar','none');
set(hfig,'userdata',ud);
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[276.75 52.5 120.75 233.25], ...
    'String',sortedpars, ...
    'Min',0,...
    'Max',10,...
    'Style','listbox', ...
    'Tag','SelList', ...
    'Value', 1);
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[38.25 287.25 150 15], ...
    'String','Removed parameters', ...
    'Style','text', ...
    'Tag','StaticText1');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'Position',[36 51 120.75 233.25], ...
    'String',' ', ...
    'Min',0,...
    'Max',10,...
    'Style','listbox', ...
    'Tag','UnselList', ...
    'Value', 1);
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[279 287.25 150 15], ...
    'String','Parameters for dendrogram', ...
    'Style','text', ...
    'Tag','StaticText1');

uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_select, ...
    'ListboxTop',0, ...
    'Position',[187.5 169.5 59.25 22.5], ...
    'String','Select >>', ...
    'Tag','UnselectBtn');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_unselect, ...
    'ListboxTop',0, ...
    'Position',[188.25 137.25 55.5 22.5], ...
    'String','<< Remove', ...
    'Tag','SelectBtn');
if  ~isempty(perc)
    uicontrol('Parent',hfig, ...
        'Units','points', ...
        'BackgroundColor',[0.914 0.914 0.914], ...
        'HorizontalAlignment','left', ...
        'ListboxTop',0, ...
        'Position',[188.25 230.25 70.5 15], ...
        'String','Select', ...
        'Style','text', ...
        'Tag','StaticText2');
    uicontrol('Parent',hfig, ...
        'Units','points', ...
        'BackgroundColor',[0.914 0.914 0.914], ...
        'Callback',@c_signif, ...
        'ListboxTop',0, ...
        'Position',[188.25 215.25 64.5 13.5], ...
        'String',ps, ...
        'Style','popupmenu', ...
        'Tag','SignifPopup', ...
        'Value', 1);
end

uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_OK, ...
    'ListboxTop',0, ...
    'Position',[331.5 13.5 64.5 22.5], ...
    'String','OK', ...
    'Tag','Pushbutton3');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_Help, ...
    'ListboxTop',0, ...
    'Position',[249.75 13.5 64.5 22.5], ...
    'String','Help', ...
    'Tag','Pushbutton3');
uiwait(hfig);
if ishandle(hfig)
    h = findobj(hfig, 'tag','SelList');
    selpars=get(h,'string');
    selndx=zeros(1,length(selpars));
    k=0;
    for j=1:length(selpars)
        for i=1:length(ud.pars)
            if strcmp(ud.pars{i},selpars{j})
                k=k+1;
                selndx(k)=i;
            end

        end

    end

    selndx=sort(selndx(1:k));
    close;
else
    selndx=[];
end

function c_signif(hobject,~)
hfig=getparentfig(hobject);
h = findobj(hfig, 'tag','SignifPopup');
aval=get(h, 'value');
ud=get(hfig,'userdata');
ndx1=ud.critvals(aval)>ud.Li;
par1=ud.pars(ndx1);
Li1=ud.Li(ndx1);
par2=ud.pars(~ndx1);
Li2=ud.Li(~ndx1);
h = findobj(hfig, 'tag','UnselList');
[~,ndx] = sort(Li1);
set(h,'value',1);
set(h,'string',par1(ndx));
h = findobj(hfig, 'tag','SelList');
[~,ndx] = sort(Li2);
set(h,'value',1);
set(h,'string',par2(ndx));
function c_OK(~,~)
uiresume;
function c_Help(~,~)
disp('help not yet implemented');
function c_select(hobject,~)
movefrom(getparentfig(hobject),'UnselList','SelList');
function c_unselect(hobject,~)
movefrom(getparentfig(hobject),'SelList','UnselList');

function movefrom(hfig,listfrom, listto)
h = findobj(hfig, 'tag',listfrom);
pars = get(h, 'string');    
if ischar(pars)
   pars={strtrim(pars)};
end
ndx=~cellfun('isempty',pars);
pars=pars(ndx);
if ~isempty(pars)
    ipars = get(h, 'value');
    ndx=true(size(pars));
    ndx(ipars)=false;
    movepars=pars(~ndx);
    staypars=pars(ndx);
    set(h,'string',staypars);
    set(h,'value',max(1,min(ipars(1),length(staypars))));
    h = findobj(hfig, 'tag',listto);
    pars2 = get(h, 'string');
    if ischar(pars2)
        pars2={strtrim(pars2)};
    end
    pars2 = [pars2; movepars]; 
    ndx=~cellfun('isempty',pars2);
    pars2=pars2(ndx);
    v=get(h,'value');
    set(h, 'string',sort(pars2));
    set(h,'value',max(1,min(v(1),length(pars2))));
end

