function out = i_paranaldialog(answer,flag)
global g_grind;
if nargin==0
    answer=[];
end

if isempty(answer)|| isstruct(answer)
    if isstruct(answer)
        out = i_paranaldialog('initstruct',answer);
    else
        out=i_paranaldialog('initstruct');
    end

    hfig=paranaldlg;
    if isempty(g_grind.pars)
        g_grind.pars = {' '};
    end
    if g_grind.statevars.vector
        pars = {};
        for i = 1:length(g_grind.pars)
            siz= evalin('base',sprintf('size(%s);',g_grind.pars{i}));
            elems = allelems(g_grind.pars{i}, siz);
            pars = [pars ;elems(:)];
        end
        
    else
        pars = g_grind.pars;
    end
    if isempty(pars)
        pars = {' '};
    end
    h1=findobj(hfig,'tag','ParamPopup');
    set(h1,'string',pars);
    par=out.par{1};
%     f=strfind(par,'(');
%     if ~isempty(f)
%         par=par(1:f(1)-1);
%     end

    f = findincell(par, pars);
    if f > 0
        set(h1,'value',f);
        popupchanged(h1);
    end

    if ischar(out.outputtype)
        outputlist = i_paranaldialog('outputlist');
        out.outputtype = find(strcmpi(out.outputtype,outputlist),1);
    end

    set(findobj(hfig,'tag','StartEdit'),'string',num2str(out.start(1)));
    set(findobj(hfig,'tag','EndEdit'),'string',num2str(out.nend(1)));
    set(findobj(hfig,'tag','StepsEdit'),'string',num2str(out.steps(1)));
    set(findobj(hfig,'tag','StabilEdit'),'string',num2str(out.stabil));
    set(findobj(hfig,'tag','WritingEdit'),'string',num2str(out.writing));
    set(findobj(hfig,'tag','OutputPopup'),'value',out.outputtype)
    set(findobj(hfig,'tag','LinesPopup'),'value',out.lines+1);
    h1=findobj(hfig,'tag','ParamPopup2');
    set(h1,'string',[{'none'};pars(:)]);
    f = findincell(out.par{2}, pars);
    if ~isempty(f)
      set(h1,'value',f+1);
      popupchanged(h1);
    end
    set(findobj(hfig,'tag','StartEdit2'),'string',num2str(out.start(2)));
    set(findobj(hfig,'tag','EndEdit2'),'string',num2str(out.nend(2)));
    set(findobj(hfig,'tag','StepsEdit2'),'string',num2str(out.steps(2)));
    %   set(findobj(hfig,'tag','DisturbanceEdit'),'string',out.disturbance);
    if ~isfield(answer,'paranal2d')
        if isempty(out.par{2})
            c_advanced(hfig);
        end

    else
        set(findobj(hfig,'tag','AdvancedButton'),'visible','off');
    end

    set(hfig, 'userdata', out);
    set(hfig,'WindowStyle','modal');
    uiwait;
    if ishandle(hfig)
       out = get(hfig, 'userdata');
       close(hfig);
    end

else
    switch answer
        case 'outputlist'
            out={'Unchanged' 'Mean' 'Median' 'Maxima' 'Minima' ...
                'Minima+Maxima' 'SD' 'CV' 'Autoregr' 'Skewness' 'Sum' ...
                'Perc05' 'Perc95' 'Range90' 'Min' 'Max' 'Range'};
            %'Returntime'};
        case 'initstruct'
            out.par={'',''};
            out.start=[0,0];
            out.nend=[10,10];
            out.steps=[50 50];
            out.stabil=600;
            out.writing=300;
            out.outputtype=1;
            out.lines=0;
            %     out.disturbance='';
            if (nargin>1)&&~isempty(flag)
                answer=flag;
                if isfield(answer,'par')&&~isempty(answer.par)
                    if ischar(answer.par)
                        out.par{1}=strtrim(answer.par);
                    else
                        out.par{1}=strtrim(answer.par{1});
                        if length(answer.par)==2
                            out.par{2} = strtrim(answer.par{2});
                        end
                    end

                end

                if isfield(answer,'start')
                    out.start(1)=answer.start(1); 
                    if length(answer.start)==2
                        out.start(2)=answer.start(2); 
                    end
                end

                if isfield(answer,'nend')
                    out.nend(1)=answer.nend(1);
                    if length(answer.nend)==2
                        out.nend(2)=answer.nend(2);
                    end
                end

                if isfield(answer,'steps')
                    out.steps(1)=answer.steps(1); 
                    if length(answer.steps)==2
                        out.steps(2)=answer.steps(2);
                    end
                end

                if isfield(answer,'stabil')
                    out.stabil=answer.stabil; 
                end

                if isfield(answer,'writing')
                    out.writing=answer.writing; 
                end

                if isfield(answer,'outputtype')
                    out.outputtype=answer.outputtype;
                end

                if isfield(answer,'lines')
                    out.lines=answer.lines;
                end

                if isfield(answer,'perturbcallback')
                    out.perturbcallback=answer.perturbcallback;
                end

            end

            
    end

end


function c_advanced(hobject,~)
hfig=getparentfig(hobject);
vis=get(findobj(hfig,'tag','advanced'),'visible');
if strcmpi(vis(1), 'on')
    setvisible(hfig,'off')
    set(findobj(hfig,'tag','AdvancedButton'),'string','Advanced');
    p = get(hfig, 'Position');
    p(4) = 300;
    p(2) = p(2) + 70;
    set(hfig, 'Position', p);
    hs=findobj(hfig,'type','uicontrol');
    p = get(hs, 'position');
    for i = 1:length(p)
        p{i}(2) = p{i}(2) - 140;
        if ~strcmpi(get(hs(i),'style'),'pushbutton')
            set(hs(i), 'position', p{i})
        end

    end

else
    setvisible(hfig,'on');
    set(findobj(hfig,'tag','AdvancedButton'),'string','Hide advanced')
    p = get(hfig, 'Position');
    p(4) = 480;
    p(2) = p(2) - 70;
    set(hfig, 'Position', p);
    hs=findobj(hfig,'type','uicontrol');
    p = get(hs, 'position');
    for i = 1:length(p)
        p{i}(2) = p{i}(2) + 140;
        if ~strcmpi(get(hs(i),'style'),'pushbutton')
            set(hs(i), 'position', p{i})
        end

    end

    
end

function c_ok(hobject,~)
hfig=getparentfig(hobject);
pars=get(findobj(hfig,'tag','ParamPopup'),'string');
ud.par{1}=pars{get(findobj(hfig,'tag','ParamPopup'),'value')};
ud.start(1)=evalin('base',get(findobj(hfig,'tag','StartEdit'),'string'));
ud.nend(1)=evalin('base',get(findobj(hfig,'tag','EndEdit'),'string'));
ud.steps(1)=evalin('base',get(findobj(hfig,'tag','StepsEdit'),'string'));
s=get(findobj(hfig,'tag','StabilEdit'),'string');
if isempty(s)
    s='0';
end

ud.stabil=evalin('base',s);
nwriting=get(findobj(hfig,'tag','WritingEdit'),'string');
if isempty(nwriting)
    nwriting='0';
end

ud.writing=evalin('base',nwriting);
ud.outputtype= get(findobj(hfig,'tag','OutputPopup'),'value');
ud.lines= get(findobj(hfig,'tag','LinesPopup'),'value')-1;
f= get(findobj(hfig,'tag','ParamPopup2'),'value');
if isempty(f)||f <= 1
    ud.par{2} = '';
else
    pars=get(findobj(hfig,'tag','ParamPopup2'),'string');
    ud.par{2} = pars{f};
end

ud.start(2)=evalin('base',get(findobj(hfig,'tag','StartEdit2'),'string'));
ud.nend(2)= evalin('base',get(findobj(hfig,'tag','EndEdit2'),'string'));
ud.steps(2)= evalin('base',get(findobj(hfig,'tag','StepsEdit2'),'string'));
%     ud.disturbance =get(findobj(hfig,'tag','DisturbanceEdit'),'string');
set(hfig, 'userdata', ud);
uiresume;
function c_cancel(hobject,~)
hfig=getparentfig(hobject);
set(hfig,'userdata',{});
uiresume;
function res = findincell(s, c)
res=find(strcmp(c,s),1);
% res = 0;
% for i = 1:length(c)
%     if strcmp(c{i}, s)
%         res = i;
%         break;
%     end
% 
% end


function setvisible(hfig,aval)
set(findobj(hfig,'tag','advanced'),'visible',aval);
set(findobj(hfig,'tag','StartEdit2'),'visible',aval);
set(findobj(hfig,'tag','EndEdit2'),'visible',aval);
set(findobj(hfig,'tag','StepsEdit2'),'visible',aval);
set(findobj(hfig,'tag','OutputPopup'),'visible',aval);
set(findobj(hfig,'tag','ParamPopup2'),'visible',aval);
%set(findobj(hfig,'tag','DisturbanceEdit'),'visible',aval);

function hfig=paranaldlg
f=329;
r=22;
f2=305;

hfig = figure('Color',[0.914 0.914 0.914], ...
    'MenuBar','none', ...
    'Name','Parameter analysis', ...
    'NumberTitle','off', ...
    'PaperPosition',[18 180 576 432], ...
    'PaperUnits','points', ...
    'Position',[232 258 504 484], ...
    'Tag','Fig1', ...
    'ToolBar','none',...
    'CreateFcn',@(h,evnt)movegui(h, 'center'));

uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f 147.75 16], ...
    'String','Name of the parameter to change:', ...
    'Style','text', ...
    'Tag','ParamText');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220.5 f 121.5 16], ...
    'String',{' '}, ...
    'Style','popupmenu', ...
    'Callback',@popupchanged,...
    'TooltipString','Parmeter 1',...
    'Tag','ParamPopup', ...
    'Value',1);
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f-r 147.75 16], ...
    'String','Start value:', ...
    'Style','text', ...
    'Tag','StartText');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f-r 121.5 16], ...
    'String','1', ...
    'Style','edit', ...
    'Tag','StartEdit');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f-r*2 147.75 16], ...
    'String','End value:', ...
    'Style','text', ...
    'Tag','EndText');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f-r*2 121.5 16], ...
    'String','10', ...
    'Style','edit', ...
    'Tag','EndEdit');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f-r*3 147.75 16], ...
    'String','Number of steps for changing:', ...
    'Style','text', ...
    'Tag','StepsText');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f-r*3 121.5 16], ...
    'String','50', ...
    'Style','edit', ...
    'Tag','StepsEdit');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f-r*4 147.75 16], ...
    'String','Period of stabilizing per step (time units)', ...
    'Style','text', ...
    'Tag','StabilText');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f-r*4 121.5 16], ...
    'String','600', ...
    'Style','edit', ...
    'Tag','StabilEdit');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f-r*5 182.25 16], ...
    'String','Period of plotting per step (time units, min.=0)', ...
    'Style','text', ...
    'Tag','StaticText1');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f-r*5 121.5 16], ...
    'String','300', ...
    'Style','edit', ...
    'Tag','WritingEdit');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f-r*6 180.75 16], ...
    'String','Type of plot:', ...
    'Style','text', ...
    'Tag','StaticText2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'ListboxTop',0, ...
    'Position',[220 f-r*6 121.5 16], ...
    'String',{'scatter plot (dots)' 'line plot' 'contour (2D only)' 'surf (2D only)'}, ...
    'Style','popupmenu', ...
    'Tag','LinesPopup', ...
    'Value',1);
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f2-r*7 147.75 16], ...
    'String','Name of a second parameter to change:', ...
    'Style','text', ...
    'Tag','advanced');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f2-r*7 121.5 16], ...
    'String',{' '}, ...
    'Callback',@popupchanged,...
    'TooltipString','',...   
    'Style','popupmenu', ...
    'Tag','ParamPopup2', ...
    'Value',1);

uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f2-r*8 147.75 16], ...
    'String','Start value:', ...
    'Style','text', ...
    'Tag','advanced');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f2-r*8 121.5 16], ...
    'String','0', ...
    'Style','edit', ...
    'Tag','StartEdit2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f2-r*9 147.75 16], ...
    'String','End value:', ...
    'Style','text', ...
    'Tag','advanced');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f2-r*9 121.5 16], ...
    'String','10', ...
    'Style','edit', ...
    'Tag','EndEdit2');

uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f2-r*10 121.5 16], ...
    'String','50', ...
    'Style','edit', ...
    'Tag','StepsEdit2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f2-r*10 147.75 16], ...
    'String','Number of steps for changing:', ...
    'Style','text', ...
    'Tag','advanced');

% uicontrol('Parent',hfig, ...
% 	'Units','points', ...
% 	'BackgroundColor',[0.914 0.914 0.914], ...
% 	'HorizontalAlignment','left', ...
% 	'ListboxTop',0, ...
% 	'Position',[23 f2-r*11 147.75 16], ...
% 	'String','Disturbance:', ...
% 	'Style','text', ...
% 	'Tag','advanced');
% uicontrol('Parent',hfig, ...
% 	'Units','points', ...
% 	'BackgroundColor',[1 1 1], ...
% 	'HorizontalAlignment','left', ...
% 	'ListboxTop',0, ...
% 	'Position',[220 f2-r*11 121.5 16], ...
% 	'Style','edit', ...
% 	'Tag','DisturbanceEdit');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[23 f2-r*11 182.25 16], ...
    'String','Output:', ...
    'Style','text', ...
    'Tag','advanced');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[220 f2-r*11 121.5 16], ...
    'String', i_paranaldialog('outputlist'), ...
    'Style','popupmenu', ...
    'Tag','OutputPopup', ...
    'Value',1);

uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_cancel, ...
    'ListboxTop',0, ...
    'Position',[96 20 74.25 18.75], ...
    'String','Cancel', ...
    'Tag','Pushbutton2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_ok, ...
    'ListboxTop',0, ...
    'Position',[180 20 74.25 18.75], ...
    'String','OK', ...
    'Tag','Pushbutton2');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'Callback',@c_advanced, ...
    'ListboxTop',0, ...
    'Position',[265.5 20 74.25 18.75], ...
    'String','Hide advanced', ...
    'Tag','AdvancedButton');

function popupchanged(hObject,~)
pars=get(hObject,'string');
aval=get(hObject,'value');
if ~isempty(pars)&&~isempty(aval)
    apar=pars{aval};
    if ~strcmp(apar,'none')
        try
           curval=evalin('base',apar);
           set(hObject,'Tooltipstring',sprintf('%s=%g',apar,curval));
        catch
        end
    else
        set(hObject,'Tooltipstring','No parameter')
    end
end
