function answer = i_parseargdlg(grindcomm,fieldnams,validate_funs,options,defaultanswer)
ud.currentanswer=defaultanswer;
ud.fieldnames=fieldnams;
ud.validate_funs=validate_funs;
if ischar(options)
    ud.options=regexp(options,',','split');
else
    ud.options=options;
end
ud.title=grindcomm;
ud.currnr=1;
ud.changed=false;
ud.value=getansstr(ud,ud.currnr);
hfig=createfigure(ud);
selectdata(hfig)
uiwait(hfig)
if ishandle(hfig)
    ud=get(hfig,'userdata');
    answer=ud.currentanswer;
    close(hfig);
else
    answer=[];
end
end

function hfig=createfigure(ud)
ud.answertxt=ud.fieldnames(1,:);
if length(ud.answertxt)==1&&isempty(ud.answertxt{1})
    ud.answertxt={};
end
for i=1:length(ud.answertxt)
    ud.answertxt{i}=sprintf('%s = %s',ud.fieldnames{1,i},getansstr(ud,i));
end
options_data=[num2cell(false(size(ud.options)));ud.options;ud.options]';
helptxt=str2cell(evalc(sprintf('help %s',ud.title)));
for i=1:size(options_data,1)
    opts=regexp(ud.options{i},'[\|]','split');
    ss=find(~cellfun('isempty',strfind(helptxt,sprintf('      ''%s',opts{1}))));
    if isempty(ss)
        options_data{i,3}='';
    else
        s=helptxt{ss(1)};
        f=strfind(s,' - ');
        if ~isempty(f)
            s=s(f(1)+3:end);
        else
            s='';
        end
        options_data{i,3}=s;
    end
end
noopts=isempty(ud.options)||numel(ud.options)==1&&isempty(ud.options{1});
hfig = figure(...
    'Units','characters',...
    'PaperUnits',get(0,'defaultfigurePaperUnits'),...
    'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
    'IntegerHandle','off',...
    'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
    'MenuBar','none',...
    'Name',['Edit options of ',ud.title],...
    'NumberTitle','off',...
    'ResizeFcn',@resize,...
    'PaperPosition',get(0,'defaultfigurePaperPosition'),...
    'PaperSize',get(0,'defaultfigurePaperSize'),...
    'PaperType',get(0,'defaultfigurePaperType'),...
    'Position',[111 21.4615384615385 120.2 32.9230769230769],...
    'Resize','on',...
    'UserData',ud,...
    'Tag','i_parseargdlg',...
    'Visible','on',...
    'CreateFcn',@(h,evnt)movegui(h, 'center'));

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'HorizontalAlignment','left',...
    'Position',[56.8 15.8 47 1.84615384615385],...
    'String',blanks(0),...
    'Style','text',...
    'Tag','keywordtext' );
if ~isempty(ud.answertxt)
    uicontrol(...
        'Parent',hfig,...
        'Units','characters',...
        'HorizontalAlignment','left',...
        'Position',[2.4 31.1538461538462 29.4 1.07692307692308],...
        'String','Select argument to edit:',...
        'Style','text',...
        'Tag','text3');
    h1=uicontrol(...
        'Parent',hfig,...
        'Units','characters',...
        'BackgroundColor',[1 1 1],...
        'Callback',@selectdata,...
        'Position',[2.2 14.3846153846154 47.8 16.5384615384615],...
        'String',ud.answertxt,...
        'Style','listbox',...
        'Value',1,...
        'Tag','datalist');
end
uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'Callback',@okbutton,...
    'Position',[59.8 2.07692307692308 13.8 1.69230769230769],...
    'String','OK',...
    'Tag','okbutton' );

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'Callback',@cancelbutton,...
    'Position',[78.4 2.07692307692308 13.8 1.69230769230769],...
    'String','Cancel',...
    'Tag','cancelbutton' );

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'Callback',@helpbutton,...
    'Position',[97.8 2.07692307692308 13.8 1.69230769230769],...
    'String','Help',...
    'Tag','helpbutton' );

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'BackgroundColor',[1 1 1],...
    'Callback',@editcallback,...
    'HorizontalAlignment','left',...
    'Position',[56.8 14.4615384615385 47 1.69230769230769],...
    'String',blanks(0),...
    'Style','edit',...
    'Tag','dataedit');


uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'Callback',@checkcallback,...
    'Position',[56.8 16.4615384615385 46.2 1.76923076923077],...
    'String',blanks(0),...
    'Style','checkbox',...
    'Tag','datacheck');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'BackgroundColor',[1 1 1],...
    'Callback',@popupcallback,...
    'Position',[56.8 15 46.6 1.53846153846154],...
    'String',blanks(0),...
    'Style','popupmenu',...
    'Value',1,...
    'Tag','datapopup');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'Position',[105.4 14.5384615384615 4.4 2],...
    'String','...',...
    'visible','off',...
    'Tag','dotbutton');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'HorizontalAlignment','left',...
    'Position',[56.8 18 47 3.38461538461539],...
    'String',blanks(0),...
    'Style','text',...
    'Tag','validatetext');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'HorizontalAlignment','left',...
    'Position',[56.8 22.30 47 3.38],...
    'String',blanks(0),...
    'Style','text',...
    'Tag','datatext');


if noopts
    vis='off';
else
    vis='on';
end
uitable(...
    'Parent',hfig,...
    'Units','characters',...
    'CellEditCallback',@EditOptionsTable,...
    'ColumnFormat',{  'logical' 'char' 'char' },...
    'ColumnEditable', [true  true false],...
    'ColumnName',{  'select'; 'option'; 'description' },...
    'ColumnWidth',{  50 60 300 },...
    'Position',[1.6 2 48.4 8.84615384615385],...
    'data',options_data,....
    'RowName',[],...
    'UserData',[],...
    'visible',vis,...
    'Tag','OptionsTable');

uicontrol(...
    'Parent',hfig,...
    'Units','characters',...
    'HorizontalAlignment','left',...
    'Position',[2.2 11.0769230769231 29.4 1.07692307692308],...
    'String','Command line options:',...
    'Style','text',...
    'Tag','text1',...
    'visible',vis);

uitable(...
    'Parent',hfig,...
    'Units','characters',...
    'ColumnFormat',{  'logical' 'char' 'char' },...
    'ColumnEditable', [true  true false],...
    'ColumnName',{  'select'; 'option'; 'description' },...
    'ColumnWidth',{  'auto' 'auto' 'auto' },...
    'Data',[],...
    'Position',[57.4 12 45 7.61538461538462],...
    'RowName',[],...
    'UserData',[],...
    'Tag','EditTable',...
    'Visible','off' );
end

function answer=getansstr(ud,i)
if isfield(ud.currentanswer,ud.fieldnames{1,i})
    answer=ud.currentanswer.(ud.fieldnames{1,i});
elseif size(ud.fieldnames,1)==4
    answer=ud.fieldnames{4,i};
else
    answer='';
end
if isnumeric(answer)||islogical(answer)
    answer=mat2str(answer);
elseif iscell(answer)
    s=sprintf('''%s'',',answer{:});
    answer=sprintf('{%s}',s(1:end-1));
end
end

function filenamecallback(hObject, ~, ~)
%get file name
hfig=getparentfig(hObject);
ud=get(hfig,'userdata');
h=findobj(hfig,'Tag','dataedit');
afile=get(h,'string');
[FileName,PathName]=uigetfile('','Select filename',afile);
ud.value=[PathName,FileName];
set(h,'string',ud.value);
ud.changed=true;
set(hfig,'userdata',ud);
end

function helpbutton(hObject, ~, ~)
hfig=getparentfig(hObject);
ud=get(hfig,'userdata');
commands(ud.title);
end

function cancelbutton(hObject, ~, ~)
hfig=getparentfig(hObject);
ud=get(hfig,'userdata');
ud.currentanswer=[];
set(hfig,'userdata',ud)
uiresume()
end

function okbutton(hObject, ~, ~)
selectdata(hObject)
uiresume()
end

function popupcallback(hObject, ~, ~)
hfig=getparentfig(hObject);
ud=get(hfig,'userdata');
h=findobj(hfig,'Tag','datapopup');
v=get(h,'value');
s=get(h,'string');
if ~strcmp(ud.value,s{v})
    ud.changed=true;
    ud.value=s{v};
end
set(hfig,'userdata',ud);
end

function checkcallback(hObject, ~, ~)
hfig=getparentfig(hObject);
ud=get(hfig,'userdata');
ud.changed=true;
ud.value=logical(get(findobj(hfig,'Tag','datacheck'),'value'));
set(hfig,'userdata',ud);
end

function EditOptionsTable(hObject, ~, ~)
hfig=getparentfig(hObject);
ud=get(hfig,'userdata');
h=findobj(hfig,'Tag','OptionsTable');
data=get(h,'data');
ud.currentanswer.opts=data(logical(cell2num(data(:,1))),2)';
set(hfig,'userdata',ud)
end

function editcallback(hObject, ~, ~)
hfig=getparentfig(hObject);
ud=get(hfig,'userdata');
ud.value=get(findobj(hfig,'Tag','dataedit'),'string');
ud.changed=true;
set(hfig,'userdata',ud);
end

function selectdata(hObject, ~, ~)
global g_grind;
hfig=getparentfig(hObject);
ud=get(hfig,'userdata');
set(findobj(hfig,'Tag','datapopup'),'visible','off');
set(findobj(hfig,'Tag','datacheck'),'visible','off');
set(findobj(hfig,'Tag','dataedit'),'visible','off');
set(findobj(hfig,'Tag','dotbutton'),'visible','off');
set(findobj(hfig,'Tag','keywordtext' ),'visible','on');
if isempty(ud.answertxt)
    return;
end
h=findobj(hfig,'tag','datalist');
if ud.changed
    haserror=false;
    currans=ud.currentanswer;
    if isempty(ud.value)
        if isfield(ud.currentanswer,ud.fieldnames{1,ud.currnr})
            currans=rmfield(ud.currentanswer,ud.fieldnames{1,ud.currnr});
        end
    else
        currans.(ud.fieldnames{1,ud.currnr})=ud.value;
        try
            answ=rmfield(currans,'opts');
        catch err
            if ~strcmp(err.identifier,'MATLAB:rmfield:InvalidFieldname')
                rethrow(err)
            else
                answ=currans;
            end
        end
        answ=[fieldnames(answ),struct2cell(answ)]';
        try
            currans=i_parseargs(ud.fieldnames,'',ud.options,answ(:),false,ud.validate_funs);
        catch err
            if strcmp(err.identifier,'grind:parseargs')
                haserror=true;
                errordlg(err.message)
            else
                rethrow(err);
            end
        end
    end
    if ~haserror
        ud.currentanswer=currans;
        ud.answertxt{ud.currnr}=sprintf('%s = %s',ud.fieldnames{1,ud.currnr},getansstr(ud,ud.currnr));
        set(h,'string',ud.answertxt);
    end
end
ud.currnr=get(h,'Value');
valid=ud.fieldnames{2,ud.currnr};
s=getansstr(ud,ud.currnr);
ud.value=s;
% set(findobj(hfig,'Tag','datapopup'),'visible','off');
% set(findobj(hfig,'Tag','datacheck'),'visible','off');
% set(findobj(hfig,'Tag','dataedit'),'visible','off');
% set(findobj(hfig,'Tag','dotbutton'),'visible','off');

xx=evalc('try,i_parseargs(ud.fieldnames(:,ud.currnr),'''','''',{''??''},false,ud.validate_funs),catch,end');
valtext=regexp(xx,'[\[][^\]]*[\]]','match');
set(findobj(hfig,'Tag','keywordtext' ),'string',ud.fieldnames{1,ud.currnr});
if ~isempty(valtext)
    set(findobj(hfig,'Tag','validatetext' ),'string',valtext{2});
end
set(findobj(hfig,'Tag','datatext' ),'string',ud.fieldnames{3,ud.currnr});
if strcmp(valid,'l')
    h=findobj(hfig,'Tag','datacheck');
    set(findobj(hfig,'Tag','keywordtext' ),'visible','off');
    set(h,'visible','on');
    set(h,'string',ud.fieldnames{1,ud.currnr})
    if strcmp(s,'true')
        set(h,'value',true)
    else
        set(h,'value',false);
    end
elseif (~strcontains(valid,'#')&&strncmp(valid,'e',1))||~isempty(regexp(valid,'(?=e[\[])[^\]]*[\]]#E$','start'))
    enums=regexp(valid,'[\|\[\]]','split');
    enums=strrep(enums(2:end),'+','');
    if ~isempty(enums)&&strcmp(enums{end},'#E')
        enums{end}='';
    end
    h=findobj(hfig,'Tag','datapopup');
    set(h,'visible','on');
    set(h,'string',enums);
    f=find(strcmp(s,enums));
    if isempty(f)
        set(h,'value',1)
    else
        set(h,'value',f(1));
    end
elseif strcmp(valid,'v')
    enums= i_statevars_names;
    h=findobj(hfig,'Tag','datapopup');
    set(h,'visible','on');
    set(h,'string',enums);
    f=find(strcmp(s,enums));
    if isempty(f)
        set(h,'value',1)
    else
        set(h,'value',f(1));
    end
elseif any(strcmp(valid,{'p','p#E'}))
    enums=g_grind.pars;
    if strcmp(valid,'p#E')
        enums=[enums, {''}];
    end
    enums=strrep(enums(2:end),'+','');
    h=findobj(hfig,'Tag','datapopup');
    set(h,'visible','on');
    set(h,'string',enums);
    f=find(strcmp(s,enums));
    if isempty(f)
        set(h,'value',1)
    else
        set(h,'value',f(1));
    end
elseif ~isempty(ud.answertxt)
    if strcmp(valid,'F')
        h=findobj(hfig, 'Tag','dotbutton');
        set(h,'callback',@filenamecallback)
        set(h,'visible','on');
    end
    h=findobj(hfig,'Tag','dataedit');
    set(h,'visible','on');
    set(h,'string',s);
end
set(hfig,'userdata',ud);
end
function resize(hobj,~)
hfig=getparentfig(hobj);
data={...
    'keywordtext',[1 0 1 0],[213 154.05 176.25 18];...
    'text3',[1 0 1 0],[9 303.75 110.25 10.5];...
    'datalist',[1 0 1 1],[8.25 140.25 179.25 161.25];...
    'okbutton',[0 1 0 1],[224.25 20.25 51.75 16.5];...
    'cancelbutton',[0 1 0 1],[294 20.25 51.75 16.5];...
    'helpbutton',[0 1 0 1],[366.75 20.25 51.75 16.5];...
    'dataedit',[1 1 1 0],[213 141 176.25 16.5];...
    'datacheck',[1 1 1 0],[213 160.5 173.25 17.25];...
    'datapopup',[1 1 1 0],[213 146.25 174.75 15];...
    'dotbutton',[0 1 1 0],[395.25 141.75 16.5 19.5];...
    'validatetext',[1 0 1 0],[213 175.5 176.25 33];...
    'datatext',[1 0 1 0],[213 217.425 176.25 32.955];...
    'OptionsTable',[1 1 0 1],[6 19.5 181.5 86.25];...
    'text1',[1 0 0 1],[8.25 108 110.25 10.5];...
    'EditTable',[1 1 1 0],[215.25 117 168.75 74.25];...
    };
h= findobj(hfig,'tag','OptionsTable');
if strcmp(get(h,'visible'),'off')
    data{3,3}= [8.25 19.5 179.25 281.775];
end
newpos=i_resizedlg(hfig,data(:,1),data(:,2),data(:,3),[286.5 118.5 450.75 321]);
end %maybe need to delete this