function [data,cols] = i_setdatadlg(par1, par2)
if nargin == 2
    data1 = i_checkstr(par1);
    columns = i_checkstr(par2);
    if isempty(data1) && ~isempty(columns)
        data1=zeros(1,length(columns))+NaN;
    end

    if size(data1,2)<length(columns)
        data1=[data1, nan(size(data1,1),length(columns)-size(data1,2))];
    end

else
    data1 = rand(10, 3);
    columns={'t','X1','X2'};
end

data1(end+1:end + 100, :) = NaN;
h1 = figure( ...
    'Units','characters',...
    'PaperUnits',get(0,'defaultfigurePaperUnits'),...
    'Color', [0.941176470588235 0.941176470588235 0.941176470588235], ...
    'IntegerHandle','off',...
    'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
    'MenuBar','none',...
    'Name','setdata - edit data of external and state variables',...
    'NumberTitle','off',...
    'PaperPosition',get(0,'defaultfigurePaperPosition'),...
    'PaperSize',get(0,'defaultfigurePaperSize'),...
    'PaperType',get(0,'defaultfigurePaperType'),...
    'Position', [103 20 112 32], ...
    'Resize','on',...
    'HandleVisibility','callback',...
    'UserData', [], ...
    'CreateFcn', @(h,ev)movegui(h,'center'),...
    'Tag','i_setdatadlg',...
    'Visible','on' );
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'Callback',@c_load,...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [3.4 2.15 18.2 1.84615384615385], ...
    'String','Load',...
    'Tag','loadbutton' );
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'Callback',@c_columns,...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [23.8 2.15 18.2 1.84615384615385], ...
    'String','Variables',...
    'Tag','ColumnsButton' );
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'Callback',@c_cancel,...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [65 2.15 18.2 1.84615384615385], ...
    'String','Cancel',...
    'Tag','pushbutton3' );
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'Callback',@c_OK,...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [85.2 2.15 18.2 1.84615384615385], ...
    'String','OK',...
    'Tag','pushbutton4' );
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'Callback',@c_help,...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [44.4 2.15 18.2 1.84615384615385], ...
    'String','Help',...
    'Tag','pushbutton5' );
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [59.8 27.3076923076923 20.2 1.07692307692308], ...
    'String','Number of rows',...
    'Style','text',...
    'Tag','text2' );
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [59.8 22.3846153846154 19.4 1.07692307692308], ...
    'String','Number of columns',...
    'Style','text',...
    'Tag','text3' );
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'Callback',@c_setrows,...
    'FontUnits','pixels',...
    'BackgroundColor', [1 1 1], ...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [59.8 25.6923076923077 20.2 1.69230769230769], ...
    'String',{   sprintf('%d',size(data1,1)) },...
    'Style','edit',...
    'Tag','RowEdit');
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'Callback',@c_setcols,...
    'BackgroundColor', [1 1 1], ...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [59.8 20.6923076923077 20.2 1.69230769230769], ...
    'String',{  sprintf('%d',size(data1,2)) },...
    'Style','edit',...
    'Tag','ColEdit');

hcmenu = uicontextmenu('Parent',h1);
htabmenu=uimenu(hcmenu, 'Label', 'Table');

uimenu(htabmenu, 'Label', 'Copy', 'Callback', @(h,ev)c_copy(h,ev,'All'),...
    'Accelerator','C');
uimenu(htabmenu, 'Label', 'Paste', 'Callback',@(h,ev)c_load(h,ev,'Clipboard','All'),...
    'Accelerator','V');

uimenu(htabmenu, 'Label', 'Load', 'Callback',@(h,ev)c_load(h,ev,'Text file'),...
    'Accelerator','L');
hselmenu=uimenu(hcmenu, 'Label', 'Selection');
uimenu(hselmenu, 'Label', 'Copy', 'Callback', @(h,ev)c_copy(h,ev,'Sel'),...
    'Accelerator','C');
uimenu(hselmenu, 'Label', 'Paste', 'Callback',@(h,ev)c_load(h,ev,'Clipboard','Sel'),...
    'Accelerator','V');
set(h1, 'uicontextmenu',hcmenu);

uitable( ...
    'Parent', h1, ...
    'Units','normalized',...
    'ColumnFormat', {  [] }, ...
    'CellEditCallback',@c_ColNameChanged,...
    'ColumnEditable', true, ...
    'ColumnName',{  'Variable' },...
    'ColumnWidth', {  100}, ...
    'Data',transpose(columns),...
    'Position',[0 0.15 1 0.85],...
    'UserData', [], ...
    'Tag','ColumnTable' );

%   'Position', [19.8 9.15 33.8 18], ...
% uicontrol( ...
%     'Parent', h1, ...
%     'Units','characters',...
%     'FontUnits','pixels',...
%     'FontSize', 10.6666666666667, ...
%     'HorizontalAlignment','left',...
%     'Position', [19.8 27.3076923076923 33.2 1.07692307692308], ...
%     'String','Variable in each column',...
%     'Style','text',...
%     'Tag','text1' );
uitable( ...
    'Parent', h1, ...
    'Units','normalized',...
    'Columnname', columns, ...
    'ColumnEditable', true(1, size(data1,2)), ...
    'CellSelectionCallback',@c_cellselect,...
    'Data', data1, ...
    'Position',[0 0.15 1 0.85],...
    'uicontextmenu',hcmenu,...
    'UserData', [], ...
    'Tag','DataTable' );

%        'Position', [0 6 112 26], ...

ud=[];
uiwait(h1);
if ishandle(h1)
    ud = get(h1, 'userdata');
end
if ~isfield(ud,'modalresult')
   ud.modalresult='cancel';
end
if strcmp(ud.modalresult, 'ok')
    h2 = findobj(h1,'tag','DataTable');
    h3 = findobj(h1,'tag','ColumnTable');
    data = get(h2, 'data');
    cols = get(h3, 'data');
    kk = ~all(isnan(data), 2);
    data = data(kk, :);
    kk = ~all(isnan(data), 1);
    data = data(:, kk);
    cols = transpose(cols(kk, :));
else
    data = [];
    cols = {};
end

if ishandle(h1)
    close(h1);
end


function c_help(~,~)
commands('setdata')

function c_cellselect(hobject,ev)
hfig=getparentfig(hobject);
ud=get(hfig,'userdata');
ud.Indices=ev.Indices;
set(hfig,'userdata',ud);

function c_copy(hobject,~,sel)
hfig=getparentfig(hobject);
h2 = findobj(hfig,'tag','DataTable');
h3 = findobj(hfig,'tag','ColumnTable');
data2 = get(h2, 'data');
cols2 = get(h3, 'data');
if strcmp(sel,'Sel')
    ud=get(hfig,'userdata');
    ndx=false(size(data2));
    ndx(ud.Indices(:,1),ud.Indices(:,2))=true;
    data2=data2(ndx);
    cols2= cols2(any(ndx,1));
    data2=reshape(data2,numel(data2)/numel(cols2),numel(cols2));
end
kk = ~all(isnan(data2), 2);
data2 = data2(kk, :);
kk = ~all(isnan(data2), 1);
data2 = num2cell(data2(:, kk));
cols2 = transpose(cols2(kk, :));
varcopy([cols2;data2]);

function c_OK(hobject,~)
hfig=getparentfig(hobject);
ud=get(hfig,'userdata');
ud.modalresult='ok';
set(hfig,'userdata',ud);
uiresume;

function c_load(hobject,~,par1,sel)
if nargin<4
    sel='All';
end
cols = [];
data1 = [];
hfig=getparentfig(hobject);
if nargin<3
    par1=i_4choicesdlg('Load data','Load from what source?',{'Text file',...
        'Variable from workspace','Clipboard','Cancel'});
end

switch par1
    case 'Text file'
        [filename,path]=uigetfile('*.csv;*.dat;*.txt', 'Get data file (delimited or CSV)');
        if filename ~= 0
            filename = [path filename];
            [cols, data1] = i_loaddata(filename);
            data1 = i_checkstr(char(data1));
        end

    case 'Variable from workspace'
        answer=inputdlg({'Enter variable or function'},'Load data from workspace',1,{''});
        data1=evalin('base',answer{1});
    case 'Clipboard'
        data1=varpaste('numeric');
        if ~isempty(data1) && all(isnan(data1(1,:)))
            data1=data1(2:end,:);
            cols=varpaste;
            cols=cols(1,:);
        end

end

if ~isempty(cols)
    TAB = sprintf('\t');
    if ischar(cols)
        l = length(cols) + 1;
        l2 = l - 1;
        while l2 < l
            cols = strrep(cols, [TAB TAB], [TAB '###skip###' TAB]);
            cols = strrep(cols, TAB, ' ');
            cols=strrep(cols,'  ',' ');
            l = l2;
            l2 = length(cols);
        end

        cols=i_checkstr(['{''' strrep(strtrim(cols),' ',''' ''') '''}']);
        % cols = memo2str(cols, 0);
    end

else
    h1 = findobj(hfig,'tag','ColumnTable');
    if ishandle(h1)
        cols = transpose(get(h1, 'data'));
    end

end

if ~isempty(data1)
    if ischar(data1)
        data1 = i_checkstr(char(data1));
    end

    data1(end+1:end + 100, :) = NaN;
    h = findobj(hfig,'tag','ColEdit');
    set(h, 'String',sprintf('%d',size(data1,2)));
    h = findobj(hfig,'tag','RowEdit');
    set(h, 'String',sprintf('%d',size(data1,1)));
    h = findobj(hfig,'tag','DataTable');
    h1 = findobj(hfig,'tag','ColumnTable');
    set(h, 'data',data1);
    set(h1, 'data', transpose(cols));
    set(h,'Columnname', cols);
    set(h, 'ColumnEditable', true(size(cols)));
end

function c_cancel(hobject,~)
hfig=getparentfig(hobject);
ud=get(hfig,'userdata');
ud.modalresult='cancel';
set(hfig,'userdata',ud);
uiresume;
function c_ColNameChanged(hobject,~)
hfig=getparentfig(hobject);
h = findobj(hfig,'tag','DataTable');
h1 = findobj(hfig,'tag','ColumnTable');
cols1 = get(h1, 'data');
set(h,'Columnname', cols1);

function c_columns(hobject,~)
hfig=getparentfig(hobject);
h = findobj(hfig,'tag','DataTable');
vis = get(h, 'visible');
if strcmp(vis, 'on')
    set(h,'visible','off');
    h = findobj(hfig,'tag','ColumnsButton');
    set(h,'String','Data')
else
    set(h,'visible','on');
    h = findobj(hfig,'tag','ColumnsButton');
    set(h,'String','Variables')
end


function c_setcols(hobject,~)
hfig=getparentfig(hobject);
h = findobj(hfig,'tag','ColEdit');
ncols = str2double(get(h, 'String'));
h = findobj(hfig,'tag','DataTable');
h1 = findobj(hfig,'tag','ColumnTable');
%   set(h,'ColumnEditable', logical(true,ncols));
data1 = get(h, 'data');
cols1 = get(h1, 'data');
if size(data1, 2) > ncols
    data1 = data1(:, 1:ncols);
    cols1 = cols1(1:ncols, :);
elseif size(data1, 2) < ncols
    data1(:, end + 1:ncols) = NaN;
    cols1(end + 1:ncols, :) = {''};
end

set(h, 'data', data1);
set(h,'Columnname', cols1);
set(h,'ColumnEditable',transpose(true(size(cols1))));
set(h1, 'data', cols1);
function c_setrows(hobject,~)
hfig=getparentfig(hobject);
h = findobj(hfig,'tag','RowEdit');
nrows = str2double(get(h, 'String'));
h = findobj(hfig,'tag','DataTable');
data1 = get(h, 'data');
if size(data1, 1) > nrows
    data1 = data1(1:nrows, :);
elseif size(data1, 2) < nrows
    data1(end + 1:nrows, :) = NaN;
end

set(h, 'data', data1);




