function i_sensplot(data,parsets,vlabels,plabels,silent)
if nargin<5
    silent=false;
end

if any(~isreal(data(:)))||any(~isreal(parsets(:)))
    warning('grind:sensplot', 'Imaginary parts of complex values ignored');
    data=real(data);
    parsets=real(parsets);
end
ud.output = data;
ud.parsets = parsets;
if exist('i_figno','file')
    n = i_figno('mcarlo') + 1;
else
    n = 2;
end

if ishandle(n)
    close(n);
end

hfig = i_figure(n);
if silent
    set(hfig,'visible','off');
end
set(hfig,'Color',[0.914 0.914 0.914], ...
    'PaperPosition',[18 180 576 432], ...
    'PaperUnits','points', ...
    'Position',[269 251 560 420], ...
    'Tag','i_sensplot', ...
    'ToolBar','figure');
set(hfig, 'userdata', ud);
uimenu('Parent',hfig, ...
    'HandleVisibility','off', ...
    'Tag','ScribeHGBinObject', ...
    'Visible','off');
uimenu('Parent',hfig, ...
    'HandleVisibility','off', ...
    'Tag','ScribeFigObjStorage', ...
    'Visible','off');
uimenu('Parent',hfig, ...
    'HandleVisibility','off', ...
    'Tag','ScribeHGBinObject', ...
    'Visible','off');
h1 = axes('Parent',hfig, ...
    'Box','on', ...
    'CameraUpVector',[0 1 0], ...
    'Color',[1 1 1], ...
    'CreateFcn','', ...
    'Position',[0.1536 0.1762 0.7732 0.7024], ...
    'Tag','Axes1', ...
    'XColor',[0 0 0], ...
    'YColor',[0 0 0], ...
    'ZColor', [0 0 0]);
line('Parent',h1, ...
    'Color',[0 0 1], ...
    'LineStyle','none', ...
    'Marker','.', ...
    'Tag','Axes1Line1', ...
    'XData',[], ...
    'YData', []);
line('Parent',h1, ...
    'Color',[1 0 0], ...
    'LineStyle','-', ...
    'Marker','none', ...
    'Tag','line', ...
    'XData',[], ...
    'YData', []);
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Callback',@c_update, ...
    'Position',[101.25 9 99.75 15], ...
    'String',vlabels, ...
    'Style','popupmenu', ...
    'Tag','VarPopup', ...
    'Value', 1);
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'ListboxTop',0, ...
    'Callback',@c_update, ...
    'Position',[295.5 9 100.5 15], ...
    'String',plabels, ...
    'Style','popupmenu', ...
    'Tag','ParPopup', ...
    'Value', 1);
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'ListboxTop',0, ...
    'Position',[239.25 6.75 45 15], ...
    'String','X-axis', ...
    'Style','text', ...
    'Tag','StaticText1');
uicontrol('Parent',hfig, ...
    'Units','points', ...
    'BackgroundColor',[0.914 0.914 0.914], ...
    'ListboxTop',0, ...
    'Position',[47.25 8.25 45 15], ...
    'String','Y-axis', ...
    'Style','text', ...
    'Tag','StaticText1');
c_update(hfig);

function c_update(hobject,~)
hfig=getparentfig(hobject);
ud = get(hfig, 'userdata');
h=findobj(hfig,'Tag','ParPopup');
ipar = get(h, 'Value');
pars = get(h, 'string');
if iscell(pars)
    if ipar<=length(pars)
       xlabel(pars{ipar});
    end

else
    xlabel(pars)
end

h=findobj(hfig,'Tag','VarPopup');
ivar = get(h, 'Value');
vars = get(h, 'string');
if ~isempty(vars)
    ylabel(vars{ivar});
    
    h=findobj(hfig,'Tag','Axes1Line1');
    yy =  ud.output(:, ivar);
    xx = ud.parsets(:, ipar);
    set(h, 'XData', xx);
    set(h, 'YData', yy);
    xrange = [min(xx(~isnan(yy))) max(xx(~isnan(yy)))];
    yrange = [min(yy(~isnan(yy))) max(yy(~isnan(yy)))];
    if yrange(2) - yrange(1) > 0
        xlim(xrange);
        ylim(yrange);
        [sens,a,b]=i_mcsensanal(yy,xx);
        yregr = transpose(xrange) .* a + b;
        h=findobj(hfig,'Tag','line');
        set(h, 'XData', xrange);
        set(h, 'YData', yregr);
    else
        sens = NaN;
    end

    
    % h=findobj(hfig,'Tag','TitleText');
    htitle=title(sprintf('Sensitivity "%s" for "%s" is %g',vars{ivar},strtrim(pars{ipar}),sens));
    set(htitle,'fontweight','normal');
end


