function i_solverdlg
global g_grind;
solverlist = solver('list');
aval = find(strcmp(solver('name'), solverlist));
if isempty(aval)
    aval=3;
end

if isempty(g_grind.solver.opt.StepSize)
    g_grind.solver.opt.StepSize = 0.3;
end

if isempty(g_grind.solver.opt.RelTol)
    g_grind.solver.opt.RelTol = 5e-5;
end

if isempty(g_grind.solver.opt.AbsTol)
    g_grind.solver.opt.AbsTol = 1e-7;
end

h1 = figure( ...
    'Units','characters',...
    'PaperUnits',get(0,'defaultfigurePaperUnits'),...
    'Color', [0.941 0.941 0.941], ...
    'IntegerHandle','off',...
    'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
    'MenuBar','none',...
    'Name','solver',...
    'NumberTitle','off',...
    'PaperPosition',get(0,'defaultfigurePaperPosition'),...
    'PaperSize',get(0,'defaultfigurePaperSize'),...
    'PaperType',get(0,'defaultfigurePaperType'),...
    'Position', [30.8 20 76.4 30.6923076923077], ...
    'Resize','off',...
    'HandleVisibility','callback',...
    'UserData', [], ...
    'Tag','figure1',...
    'Visible','on',...
    'CreateFcn',@(h,evnt)movegui(h, 'center'));

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'Callback',@c_ok,...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [7.6 1.30769230769231 17.8 2.38461538461538], ...
    'String','OK',...
    'Tag','OKbutton' );

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'Callback',@c_cancel,...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [29.8 1.30769230769231 17.8 2.38461538461538], ...
    'String','Cancel',...
    'Tag','Cancelbutton' );

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'Callback',@c_help,...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [52 1.30769230769231 17.8 2.38461538461538], ...
    'String','Help',...
    'Tag','Helpbutton');

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [9.8 25 22 1.76923076923077], ...
    'String','Solver',...
    'Style','text',...
    'Tag','text1' );

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'Callback',@c_solverchanged, ...
    'BackgroundColor', [1 1 1], ...
    'FontSize', 10.6666666666667, ...
    'Position', [32.2 25 27.4 1.69230769230769], ...
    'String', solverlist, ...
    'Style','popupmenu',...
    'Value', aval, ...
    'Tag','SolverPopup' );

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [9.8 18.0769230769231 22 1.76923076923077], ...
    'String','Absolute tolerance',...
    'Style','text',...
    'Tag','AbsToltext' );

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'BackgroundColor', [1 1 1], ...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [32.2 18.3846153846154 27.6 1.76923076923077], ...
    'String', num2str(g_grind.solver.opt.AbsTol), ...
    'Style','edit',...
    'Tag','AbsTolEdit' );

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'BackgroundColor', [1 1 1], ...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [32.2 21.6923076923077 27.6 1.76923076923077], ...
    'String', num2str(g_grind.solver.opt.StepSize), ...
    'Style','edit',...
    'Tag','StepSizeEdit',...
    'Visible','off');
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'BackgroundColor', [1 1 1], ...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [32.2 21.6923076923077 27.6 1.76923076923077], ...
    'String', num2str(g_grind.solver.iters), ...
    'Style','edit',...
    'Tag','ItersEdit',...
    'Visible','off');

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [9.8 21.7692307692308 22.2 1.30769230769231], ...
    'String','Relative Tolerance',...
    'Style','text',...
    'Tag','RelToltext' );

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [9.8 14.3 35.2 1.84615384615385], ...
    'String','Backwards',...
    'Style','checkbox',...
    'Value', g_grind.solver.backwards, ...
    'Tag','Backwcheck' );

uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'BackgroundColor', [1 1 1], ...
    'FontSize', 10.6666666666667, ...
    'HorizontalAlignment','left',...
    'Position', [32.2 21.6923076923077 27.6 1.76923076923077], ...
    'String', num2str(g_grind.solver.opt.RelTol), ...
    'Style','edit',...
    'Tag','RelTolEdit' );


uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [9.8 10.5 35.2 1.84615384615385], ...
    'String','Add mode',...
    'Value', g_grind.solver.addmode, ...
    'Style','checkbox',...
    'Tag','AddModecheck' );
uicontrol( ...
    'Parent', h1, ...
    'Units','characters',...
    'FontUnits','pixels',...
    'FontSize', 10.6666666666667, ...
    'Position', [9.8 6.7 35.2 1.84615384615385], ...
    'String','Force non-negative values',...
    'Value', ~isempty(g_grind.solver.opt.NonNegative), ...
    'Style','checkbox',...
    'Tag','NonNegativecheck' );
if g_grind.solver.isdiffer
    h=findobj(h1,'Tag','AbsToltext');
    set(h,'String','Iterations');
    h=findobj(h1,'Tag','AbsTolEdit');
    set(h,'visible','off');
    h=findobj(h1,'Tag','ItersEdit');
    set(h,'visible','on');
    h=findobj(h1,'Tag','StepSizeEdit');
    set(h,'visible','off');
    h=findobj(h1,'Tag','RelToltext');
    set(h,'visible','off');
    h=findobj(h1,'Tag','RelTolEdit');
    set(h,'visible','off');
end
c_solverchanged(h1);
uiwait(h1);
close(h1);
function c_solverchanged(hobject,~)
global g_grind;
hfig=getparentfig(hobject);
h=findobj(hfig,'Tag','SolverPopup');
aval = get(h, 'Value');
lst=get(h,'string');
prop=solver('-properties',lst{aval});
h=findobj(hfig, 'Tag','NonNegativecheck' );
if ~prop.handles_nonnegative
    set(h, 'enable','off');
else
    set(h, 'enable','on');
end

if prop.hasfixedstep&&~g_grind.solver.isdiffer
    h=findobj(hfig,'Tag','RelToltext');
    set(h,'String','Step size');
    h=findobj(hfig,'Tag','RelTolEdit');
    set(h,'visible','off');
    h=findobj(hfig,'Tag','ItersEdit');
    set(h,'visible','off');
    h=findobj(hfig,'Tag','StepSizeEdit');
    set(h,'visible','on');
    h=findobj(hfig,'Tag','AbsToltext');
    set(h,'visible','off');
    h=findobj(hfig,'Tag','AbsTolEdit');
    set(h,'visible','off');
elseif ~g_grind.solver.isdiffer
    h=findobj(hfig,'Tag','RelToltext');
    set(h,'String','Relative tolerance');
    h=findobj(hfig,'Tag','RelTolEdit');
    set(h,'visible','on');
    h=findobj(hfig,'Tag','ItersEdit');
    set(h,'visible','off');
    h=findobj(hfig,'Tag','StepSizeEdit');
    set(h,'visible','off');
    h=findobj(hfig,'Tag','AbsToltext');
    set(h,'visible','on');
    h=findobj(hfig,'Tag','AbsTolEdit');
    set(h,'visible','on');
elseif g_grind.solver.isdiffer
    h=findobj(hfig,'Tag','RelToltext');
    set(h,'String','Iterations');
    set(h,'visible','on');
    h=findobj(hfig,'Tag','RelTolEdit');
    set(h,'visible','off');
    h=findobj(hfig,'Tag','ItersEdit');
    set(h,'visible','on');
    h=findobj(hfig,'Tag','StepSizeEdit');
    set(h,'visible','off');
    h=findobj(hfig,'Tag','AbsToltext');
    set(h,'visible','off');
    h=findobj(hfig,'Tag','AbsTolEdit');
    set(h,'visible','off');
end

function c_ok(hobject,~)
global g_grind;
hfig=getparentfig(hobject);
h=findobj(hfig, 'Tag','AbsTolEdit' );
g_grind.solver.opt.AbsTol = str2double(get(h, 'String'));
h=findobj(hfig, 'Tag','StepSizeEdit');
g_grind.solver.opt.StepSize = str2double(get(h, 'String'));
h=findobj(hfig, 'Tag','ItersEdit');
g_grind.solver.iters = str2double(get(h, 'String'));
h=findobj(hfig, 'Tag','Backwcheck' );
backw1=get(h, 'Value');
if g_grind.solver.backwards~=backw1
    g_grind.solver.backwards = backw1;
    if ~isempty(g_grind.solver.opt.Jacobian)
        g_grind.solver.opt.Jacobian=i_getodehandle('Jacobian');
    end

end

h=findobj(hfig, 'Tag','RelTolEdit' );
g_grind.solver.opt.RelTol = str2double(get(h, 'String'));
h=findobj(hfig, 'Tag','AddModecheck' );
g_grind.solver.addmode = get(h, 'Value');
h=findobj(hfig, 'Tag','NonNegativecheck' );
nn = get(h, 'Value');
if xor(nn>0,~isempty(g_grind.solver.opt.NonNegative))
    solver('-n',nn>0);
end

%if ~(g_grind.solver.haslags )
    h=findobj(hfig,'Tag','SolverPopup' );
    solverlist = get(h, 'String');
    aval = get(h, 'Value');
    solver(solverlist{aval});
%end

uiresume(hfig);
function c_cancel(hobject,~)
hfig=getparentfig(hobject);
uiresume(hfig);
function c_help(~,~)
commands('solver');


